spring.application.name=MicroServices_07_Student_Actiators
server.port=9095

management.endpoint.health.show-details=always

management.endpoints.web.exposure.include=*


per.id = 40
per.name = "saikumar"
per.age = 25